/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as SiteProductsRouteImport } from './routes/_site/products'
import { Route as SiteAuthenticatedRouteRouteImport } from './routes/_site/_authenticated/route'
import { Route as SiteauthSignupRouteImport } from './routes/_site/(auth)/signup'
import { Route as SiteauthLoginRouteImport } from './routes/_site/(auth)/login'
import { Route as SiteAuthenticatedProfileIndexRouteImport } from './routes/_site/_authenticated/profile/index'
import { Route as SiteAuthenticatedDashboardIndexRouteImport } from './routes/_site/_authenticated/dashboard/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAuthenticatedRouteRoute = SiteAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteauthSignupRoute = SiteauthSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteauthLoginRoute = SiteauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAuthenticatedProfileIndexRoute =
  SiteAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => SiteAuthenticatedRouteRoute,
  } as any)
const SiteAuthenticatedDashboardIndexRoute =
  SiteAuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => SiteAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/products': typeof SiteProductsRoute
  '/admin/products': typeof AdminProductsRoute
  '/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof SiteauthLoginRoute
  '/signup': typeof SiteauthSignupRoute
  '/dashboard': typeof SiteAuthenticatedDashboardIndexRoute
  '/profile': typeof SiteAuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/products': typeof SiteProductsRoute
  '/admin/products': typeof AdminProductsRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof SiteauthLoginRoute
  '/signup': typeof SiteauthSignupRoute
  '/dashboard': typeof SiteAuthenticatedDashboardIndexRoute
  '/profile': typeof SiteAuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_site/_authenticated': typeof SiteAuthenticatedRouteRouteWithChildren
  '/_site/products': typeof SiteProductsRoute
  '/admin/products': typeof AdminProductsRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/(auth)/login': typeof SiteauthLoginRoute
  '/_site/(auth)/signup': typeof SiteauthSignupRoute
  '/_site/_authenticated/dashboard/': typeof SiteAuthenticatedDashboardIndexRoute
  '/_site/_authenticated/profile/': typeof SiteAuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/products'
    | '/admin/products'
    | '/'
    | '/admin/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/products'
    | '/admin/products'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/_authenticated'
    | '/_site/products'
    | '/admin/products'
    | '/_site/'
    | '/admin/'
    | '/_site/(auth)/login'
    | '/_site/(auth)/signup'
    | '/_site/_authenticated/dashboard/'
    | '/_site/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/_authenticated': {
      id: '/_site/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SiteAuthenticatedRouteRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/(auth)/signup': {
      id: '/_site/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SiteauthSignupRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/(auth)/login': {
      id: '/_site/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteauthLoginRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/_authenticated/profile/': {
      id: '/_site/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteAuthenticatedProfileIndexRouteImport
      parentRoute: typeof SiteAuthenticatedRouteRoute
    }
    '/_site/_authenticated/dashboard/': {
      id: '/_site/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SiteAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof SiteAuthenticatedRouteRoute
    }
  }
}

interface SiteAuthenticatedRouteRouteChildren {
  SiteAuthenticatedDashboardIndexRoute: typeof SiteAuthenticatedDashboardIndexRoute
  SiteAuthenticatedProfileIndexRoute: typeof SiteAuthenticatedProfileIndexRoute
}

const SiteAuthenticatedRouteRouteChildren: SiteAuthenticatedRouteRouteChildren =
  {
    SiteAuthenticatedDashboardIndexRoute: SiteAuthenticatedDashboardIndexRoute,
    SiteAuthenticatedProfileIndexRoute: SiteAuthenticatedProfileIndexRoute,
  }

const SiteAuthenticatedRouteRouteWithChildren =
  SiteAuthenticatedRouteRoute._addFileChildren(
    SiteAuthenticatedRouteRouteChildren,
  )

interface SiteRouteRouteChildren {
  SiteAuthenticatedRouteRoute: typeof SiteAuthenticatedRouteRouteWithChildren
  SiteProductsRoute: typeof SiteProductsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteauthLoginRoute: typeof SiteauthLoginRoute
  SiteauthSignupRoute: typeof SiteauthSignupRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteAuthenticatedRouteRoute: SiteAuthenticatedRouteRouteWithChildren,
  SiteProductsRoute: SiteProductsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteauthLoginRoute: SiteauthLoginRoute,
  SiteauthSignupRoute: SiteauthSignupRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
